# Generated by Django 4.0.6 on 2022-07-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='region',
            field=models.CharField(blank=True, choices=[('', '---------'), (1, 'Namangan'), (2, 'Andijon')], max_length=2),
        ),
    ]
